version: '3.4'

services:
  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: src/Auth.Api/Dockerfile
    networks:
      - net
    environment:
        KAFKA: kafka:29092

  kafka.consumer.handler:
    image: ${DOCKER_REGISTRY-}kafkaconsumerhandler
    build:
      context: .
      dockerfile: src/Kafka.Consumer.Handler/Dockerfile
    networks:
      - net
    environment:
        KAFKA: kafka:29092

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:   
    image: confluentinc/cp-kafka:latest
    networks:
      - net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    networks:
      - net
    depends_on:
      - zookeeper
    ports:
      - 9093:9000
    links:
    - zookeeper
    - kafka
    environment:
      ZK_HOSTS: zookeeper:2181

networks:
  net:
    driver: bridge